Feat: Add TuviConverterLib and TuviConverterTests
Eppie-io/TuviBytesToEmailConverterLib pull request #1
Opened 2022-09-28 09:19 UTC by Gymbotan

I add TuviConverterLib and TuviConverterTests. Is everything ok?

2022-09-29 09:25 UTC, nesbox approved these changes
@ValeraFinebits assigned me to review this issue but unfortunately, I don't know what's going on here :)
As I see it, you are trying to encode some binary data into a string to use it as an email address in the future. I don't know what to say, I'm going just to aproove it :)
Thanks :)

2022-09-29 09:43 UTC, Dieveral commented on TuviBytesToEmailConverterLib/.gitignore
> +/TTuviBytesToEmailConverterLib/obj
Double T in the beginning, is it a typo?

2022-09-29 09:55 UTC, Dieveral commented on TuviBytesToEmailConverterLib/TuviBytesToEmailConverterLib/TuviConverter.cs
> +                throw new ArgumentException("Initial array is too big to create coorect email's name (name can not be longer than 64 symbols).", nameof(array));
Typo: ... create co**or**ect email's ...

2022-09-29 11:35 UTC, Gymbotan commented on TuviBytesToEmailConverterLib/.gitignore
> +/TTuviBytesToEmailConverterLib/obj
Yes. It's a mistake. Just extra T. Actually this whole .gitignore file is excessive. So it was deleted.

2022-09-29 11:36 UTC, Gymbotan commented on TuviBytesToEmailConverterLib/TuviBytesToEmailConverterLib/TuviConverter.cs
> +                throw new ArgumentException("Initial array is too big to create coorect email's name (name can not be longer than 64 symbols).", nameof(array));
Was fixed to "correct". Thanks.

2022-09-29 11:39 UTC, ValeraFinebits commented
> @ValeraFinebits assigned me to review this issue but unfortunately, I don't know what's going on here :) As I see it, you are trying to encode some binary data into a string to use it as an email address in the future. I don't know what to say, I'm going just to aproove it :) Thanks :)

@nesbox you are right. 
@Gymbotan could you please add README.md with explanation?

2022-09-29 12:01 UTC, Dieveral approved these changes

2022-10-06 11:38 UTC, anatolse commented on README.md
> +# TuviBytesToEmailConverterLib
I suppose to remove name `Tuvi` from library name and from namespaces

2022-10-06 12:43 UTC, anatolse commented on TuviBytesToEmailConverterLib/TuviConverterTests/Base32EConverterTests.cs
> +        [TestCase(new byte[] { 114, 134, 172, 154, 121, 225, 164, 223, 189, 76, 59, 221, 142, 91, 137, 190, 148, 201, 107, 26, 81, 255, 106, 58, 122, 91, 148, 58, 33, 150, 228, 232, 55, 77, 34, 127,
Please, add test cases when byte array has leading zeroes

2022-10-06 12:51 UTC, anatolse commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/Base32EConverter.cs
> +            if (array is null)
I would replaced these statements with asserts, we already checked this in public method

2022-10-06 13:38 UTC, anatolse commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/BigIntegerExtension.cs
> +        public static byte[] ToStraightByteArray(this BigInteger number)
I would renamed to something like `ToBigEndian`
Moreover, why not to use BigInteger.ToByteArray() & Array.Reverse() ?

2022-10-06 13:39 UTC, anatolse commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/Base32EConverter.cs
> +        private static byte[] ConvertFiveToEightBits(byte[] array)
I would returned a string from this method

2022-10-06 13:52 UTC, anatolse requested changes
Please resolve my notes

2022-10-07 06:55 UTC, Gymbotan commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/BigIntegerExtension.cs
> +        public static byte[] ToStraightByteArray(this BigInteger number)
1 +
2 BigInteger contains 1 extrabit for sign(+ or -) so in some cases if you use BigInteger.ToByteArray() it will return extra byte and will fail some tests. In newer version than stardart 2.0 there are overloaded methods that ignore sign bit or use BigEndian format (for BigInteger type). But they don't work here (((

2022-10-07 13:57 UTC, Gymbotan commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/Base32EConverter.cs
> +            char[] symbolsArray = new char[fiveBitsArray.Length];
As I remember, StringBuilder contains inside somthing like char[]. Moreover it will spend additional time for changing it's size during adding new symbols. Also it requires more resources for creating StringBuilder. So I think current solution is more effective.

2022-10-07 14:15 UTC, Gymbotan commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/Base32EConverter.cs
> +        private static byte[] ConvertFiveToEightBits(byte[] array)
This method returns public key. As i understad it (PK) should be represented as byte array. If not, how exactly this string should looks like? Like "01101010001111101110001011..." or some other representation?

2022-10-14 12:09 UTC, anatolse commented on TuviBytesToEmailConverterLib/TuviBase32EConverterLib/Base32EConverter.cs
> +            char[] symbolsArray = new char[fiveBitsArray.Length];
Ok, later we will make speed test). Closing for now

2022-10-14 12:11 UTC, anatolse approved these changes

2022-10-14 12:11 UTC, merged